[package]
name = "days"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
csv = "1.3.0"
home = "0.5.3"
clap = { version = "4.0", features = ["derive"] }